Excellency/Excellency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('service/', include("service.urls")),
    path("account/", include("account.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Excellency/account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("sign_up/", views.sign_up_view, name="sign_up_view"),
    # path("user/", views.user_profile_view, name="user_profile_view"),
    #     path("user/<user_name>/",views.user_profile_view, name="user_profile_view"),
    path("profile/<user_id>/update/",views.update_profile_view, name="update_profile_view"),
        # path("profile/update/",views.update_profile_view, name="update_profile_view"),

    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view"),
    path("lawyer/<user_id>/profile/",views.profile_view, name="profile_view"),
    path("account_balance/", views.account_balance, name="account_balance"),
    path('posts/<user_id>/', views.my_post, name='my_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post')

]

Excellency/main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path("", views.index_view, name="index_view"),
    path("lawyers", views.lawyers_view, name="lawyers_view"),
    path("contactus", views.contactus_view, name="contactus_view"),
    path("contact_messages", views.contact_messages, name="contact_messages"),
    path("admin_view", views.admin_view, name="admin_view"),
    path('lawyer_details/<user_id>', views.lawyer_details_view, name='lawyer_details'),
    path('post/', views.post_list, name='post_list'),
    path("verification/<user_id>/", views.verification, name="verification"),
    path('post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('post/<int:post_id>/', views.post_view, name='post_view'),

    path('post/<int:post_id>/bookmark/', views.bookmark_post, name='bookmark_post'),
    path('contact/success/', views.contact_success, name='contact_success'),

]

Excellency/service/urls.py
from django.urls import path
from . import views

app_name = "service"

urlpatterns = [
    #     path("", views.sign_up_view, name="sign_up_view"),
    path('order/<lawyer_id>/', views.order_form, name='order_form'),

    path('payment/<order_id>/', views.payment_view, name='payment_view'),
    path('<order_id>/chat/', views.chat_view, name='chat_view'),
    path('orders/', views.current_orders, name='current_orders_view'),
    path('previous_orders/', views.previous_orders, name='previous_orders'),
    path('order_details/<order_id>/', views.order_details, name='order_details'),
    path('offer/add/', views.add_offer, name='add_offer'),
    path('rating/', views.rating_view, name='rating_view'),
]

Excellency/main/models.py
from django.db import models
from main import validator
from account.models import User

class Contactus(models.Model):
   full_name = models.CharField(max_length=50, blank=False)
   email = models.EmailField(blank=False, validators=[
                             validator.validate_email])
   subject = models.CharField(max_length=120, blank=False)
   message = models.TextField(blank=False)
   created_at = models.DateTimeField(auto_now_add=True)
   
def post_image_upload_to(instance, filename):
   return "post/images/{}/{}".format(instance.author.id, filename)

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to=post_image_upload_to, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
     
    def total_likes(self):
        return Like.objects.filter(post=self).count()

    def total_bookmarks(self):
        return Bookmark.objects.filter(post=self).count()
     
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} likes {self.post.title}'
     
class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} bookmarks {self.post.title}'

Excellency/main/views.py
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, render, redirect
from main.models import Contactus, Post, Like, Bookmark
from service.models import Service
from account.models import User, Specialty, LawyerProfile
from django.db.models import Count, Sum
from django.db.models import F
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import global_settings as settings
from django.core.mail import send_mail

email_from = settings.EMAIL_HOST_USER


def index_view(request: HttpRequest):
    order_num = Service.objects.all().count()
    lawyers_num = User.objects.filter(role="Lawyer").count()
    customar_num = User.objects.filter(role="Customar").count()
    return render(request, "main/index.html", {"order_num": order_num,
                                               "lawyers_num": lawyers_num,
                                               "customar_num": customar_num})


def contactus_view(request: HttpRequest):
    msg = None
    try:
        if request.method == "POST":
            Contactus.objects.create(full_name=request.POST.get('full_name'),
                                     email=request.POST.get('email'),
                                     subject=request.POST.get('subject'),
                                     message=request.POST.get('message'),
                                     )
            msg = "تم ارسال رسالتك بنجاح"
            return redirect("main:contact_success")
    except Exception as e:
        msg = e
    return render(request, "main/contactus.html", {'msg': msg})


def lawyers_view(request: HttpRequest):
    try:
        lawyers = User.objects.filter(
            role="Lawyer", lawyer_profile__certified=True)
        spcialities = Specialty.objects.all()
        if "sort" not in request.GET:
            lawyers.order_by("id")

        if "lawyer_name" in request.GET:
            lawyers = lawyers.filter(
                full_name__contains=request.GET.get("lawyer_name")
            )
        if "spcialties" in request.GET:
            spcialities_filter = request.GET.getlist("spcialties")
            lawyers = lawyers.filter(
                lawyer_profile__specialty__in=spcialities_filter).annotate(Count("id"))
        if "sort" in request.GET:
            if request.GET.get("sort") == "user_name_a_z":
                lawyers = lawyers.order_by("full_name")
            elif request.GET.get("sort") == "user_name_z-a":
                lawyers = lawyers.order_by("-full_name")
            elif request.GET.get("sort") == "rating_top":
                lawyers = lawyers.annotate(total=Sum("lawyer__rating__rate")).order_by("-total")
        if "clear" in request.GET:
            print(request.path)
            return redirect(request.path)
    except Exception as e:
        print(e)
    return render(request, "main/lawyers.html", {"lawyers": lawyers, "specialities": spcialities})


@login_required(login_url='/account/login')
def contact_messages(request: HttpRequest):
    if not (request.user.is_staff or request.user.is_superuser):
        return render(request, "no_permission.html")
    messages = Contactus.objects.all()

    return render(request, 'main/contact_messages.html', {'messages': messages})


@login_required(login_url='/account/login')
def admin_view(request: HttpRequest):
    if not (request.user.is_staff or request.user.is_superuser):
        return render(request, "no_permission.html")
    lawyer_profiles = LawyerProfile.objects.all()
    return render(request, 'main/admin.html', {'lawyer_profiles': lawyer_profiles})


def lawyer_details_view(request: HttpRequest, user_id):
    user = User.objects.get(id=user_id)
    return render(request, 'main/lawyer_details.html', {"user": user})


@login_required(login_url='/account/login')
def verification(request: HttpRequest, user_id):
    if not (request.user.is_staff or request.user.is_superuser):
        return render(request, "no_permission.html")
    user = User.objects.get(id=user_id)

    recipient_list = [user.email, ]
    if "accept" in request.POST:
        user.lawyer_profile.certified = True
        user.lawyer_profile.save()
        # send mail
        subject = 'تم توثيق حسابك في موقع المعالي للمحاماة'
        message = f'''مرحبا  {user.full_name},
        تم توثيق حسابك
        {request.build_absolute_uri("/")}
        '''
        send_mail(subject, message, email_from, recipient_list)

    if "reject" in request.POST:
        user.lawyer_profile.certified = False
        user.lawyer_profile.save()
        # send mail
        subject = 'تم الغاء توثيق حسابك في موقع المعالي للمحاماة'
        message = f'''مرحبا  {user.full_name},
         نأسف لاخبارك انه تم الغاء توثيق حسابك لانتهاكك قوانين الموقع
        {request.build_absolute_uri("/")}
        '''
        send_mail(subject, message, email_from, recipient_list)

    return redirect("main:admin_view")


@login_required(login_url='/account/login')
def post_list(request: HttpRequest):
    posts = Post.objects.all()
    return render(request, 'main/post_lawyers.html', {'posts': posts})


def post_view(request: HttpRequest, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'main/post.html', {'post': post})


def like_post(request: HttpRequest, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user
    if user.is_authenticated:
        like, created = Like.objects.get_or_create(user=user, post=post)
        if not created:
            like.delete()
    return redirect(reverse('main:post_list'))


def bookmark_post(request: HttpRequest, post_id):
    try:
        if not request.user.is_authenticated:
            return redirect("account:login_view")
        post = Post.objects.get(pk=post_id)

        bookmarked_post = Bookmark.objects.filter(user=request.user, post=post).first()

        if not bookmarked_post:

            bookmark = Bookmark(user=request.user, post=post)
            bookmark.save()
        else:

            bookmarked_post.delete()

    except Exception as e:
        print(e)

    return redirect("main:post_list")


def contact_success(request):
    return render(request, 'main/contact_success.html')

Excellency/main/templates/main/admin.html
<!--djlint:off H021 H006-->
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    Admin
{% endblock title %}
{% block content %}
    {% include "account/sidebar.html" %}
    <nav class="navbar navbar-expand-lg"
         style="background-color: rgba(240, 248, 255, 0)">
    </nav>
    <div class="container-fluid py-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% for profile in lawyer_profiles %}
                    <div class="card-10 shadow-lg p-4 mb-4">
                        <div class="row align-items-center">
                            <div class="col-md-2">
                                <img src="{{ profile.image.url }}"
                                     alt="Profile Picture"
                                     class="img-fluid rounded-3"
                                     style="width: 180px">
                            </div>
                            <div class="col-md-10">
                                <div>
                                    <h3 class="mb-2">
                                        {{ profile.user.full_name }}
                                        {% if profile.certified %}
                                            <i title="محامي موثوق"
                                               class="fa-solid fa-badge-check text-success"
                                               style="font-size: 0.8em"></i>
                                        {% endif %}
                                    </h3>
                                    <div class="d-flex justify-content-start">
                                        <p class="text-muted">
                                            {% for specialty in profile.specialty.all %}
                                                {{ specialty }}
                                                {% if not forloop.last %}|{% endif %}
                                            {% endfor %}
                                        </p>
                                    </div>
                                    <div class="d-flex justify-content-end">
                                        <a href="{% url 'main:lawyer_details' profile.user.id %}"
                                           class="btn btn-outline-dark">تفاصيل</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

Excellency/main/templates/main/contact_messages.html
{% extends "base/base.html" %}
{% block title %}
    الرسائل
{% endblock title %}
{% block content %}
    {% include "account/sidebar.html" %}

    <h1 class="text-center fw-bold mt-3 text-gold">الرسائل</h1>
    <div class="row justify-content-center me-5 pe-5">
        <div class="col d-flex flex-wrap gap-3 py-5 mx-4">
            {% for message in messages %}
                <div class="mas border-1 p-5 rounded-3 ">
                    <h4>{{ message.full_name }}</h4>
                    <h4>{{ message.email }}</h4>
                    <p>{{ message.subject }}</p>
                    <p>{{ message.created_at }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
    <style>
        .mas {
            background-color: rgb(255, 255, 255);
            width: 400px;

        }
    </style>
{% endblock content %}

Excellency/main/templates/main/contact_success.html
{% extends "base/base.html" %}
{% block title %}
    الرسائل
{% endblock title %}
{% block content %}
<div class="container mt-5 py-5 bg-light rounded-3 p-5">
    <div class="jumbotron text-center">
        <h2 class="display-4">نشكرك على التواصل معنا!</h2>
        <p class="lead">تم ارسال رسالتك بنجاح. سوف نعود إليك قريبا</p>
        <hr class="my-4">
        <p>هل تريد العودة الى الصفحة الرئيسية او المنشورات</p>
        <p class="lead">
            <a class="btn btn-dark btn-lg" href="{% url 'main:post_list' %}" role="button">المنشورات</a>
            <a class="btn btn-dark btn-lg" href="{% url 'main:index_view' %}" role="button">الرئيسية</a>
        </p>
    </div>
</div>
{% endblock content %}

Excellency/main/templates/main/lawyers.html
{# djlint:off H030,H031,H006,H021 #}
{% extends "base/base.html" %}
{% load static %}
{% load tags %}
{% block title %}
    المحامين
{% endblock title %}
{% block content %}
    <nav class="navbar navbar-expand-lg align-items-center"
         style="background-color: rgba(240, 248, 255, 0)">
        <div class="container">
            <div class="navbar-nav">
                <form class="d-flex ms-auto"
                      role="search"
                      style="gap: 10px"
                      action="{% url "main:lawyers_view" %}"
                      method="get">
                    <input type="text"
                           name="lawyer_name"
                           class="form-control"
                           value="{{ request.GET.lawyer_name }}"
                           placeholder="بحث بالأسم">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle bg-light rounded-2 mx-2 text-black"
                               href="#"
                               role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">
                                {% if not request.GET|getlist:"spcialties"|length %}اختر خدمة{% endif %}
                                {% for specialty in specialities %}
                                    {% if specialty.id|slugify in request.GET|getlist:"spcialties" %}
                                        {{ specialty.name }}
                                        {% if not forloop.last %},{% endif %}
                                    {% endif %}
                                {% endfor %}
                            </a>
                            <ul class="dropdown-menu p-2">
                                {% for specialty in specialities %}
                                    <li class="dropdown-item px-2 text-end">
                                        <input type="checkbox"
                                               id="spcialties_{{ specialty.id }}"
                                               name="spcialties"
                                               {% if specialty.id|slugify  in request.GET|getlist:"spcialties" %}checked{% endif %}
                                               value="{{ specialty.id }}">
                                        <label class="custom-checkbox" for="spcialties_{{ specialty.id }}">{{ specialty.name }}</label>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li>
                            <div class="d-flex h-100 gap-2">
                                <select name="sort" class="form-select" style="width: 8rem;">
                                    <option value="user_name_a_z"
                                            {% if "user_name_a_z" in request.GET.sort %}selected{% endif %}>أ - ي</option>
                                    <option value="user_name_z-a"
                                            {% if "user_name_z-a" in request.GET.sort %}selected{% endif %}>ي - أ</option>
                                    <option value="rating_top"
                                            {% if "rating_top" in request.GET.sort %}selected{% endif %}>ًالأعلى تقييما</option>
                                </select>
                                <button class="btn btn-outline-dark" name="search" type="submit">بحث</button>
                                <button class="btn btn-outline-dark" name="clear" type="submit">مسح</button>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </form>
    </nav>
    <div class="container-fluid py-5 g-5 mx-1 p-3">
        <div class="d-flex flex-wrap gap-3 justify-content-center align-items-center g-1">
            {% for lawyer in lawyers %}
                <div class="col-md-4  rounded-4">
                    <div class="law-card card-10 shadow-lg p-5"
                         style="background-color: white">
                        <div class="row">
                            <div class="col-md-4 ">
                                <img src="{{ lawyer.lawyer_profile.image.url }}"
                                     alt="Profile Picture"
                                     class="img-fluid rounded-4 h-75"
                                     style="width: 200px">
                            </div>
                            <div class="col-md-8">
                                <a href="{% url "account:profile_view" lawyer.id %}">
                                    <h4 class="mb-2">{{ lawyer.full_name }}</h4>
                                </a>
                                <div class="d-flex justify-content-start">
                                    <p class="text-muted">
                                        {% for sp in lawyer.lawyer_profile.specialty.all %}
                                            {{ sp }}
                                            {% if not forloop.last %}|{% endif %}
                                        {% endfor %}
                                    </p>
                                </div>
                                <div class="d-flex justify-content-between align-items-center mb-1">
                                    <div>
                                        <p class="mb-1 text-muted">
                                            التقييم :
                                            <span class="mb-0">
                                                {% if lawyer|rate_average %}
                                                    {{ lawyer |rate_average }}
                                                {% else %}
                                                    لم يقيم بعد
                                                {% endif %}
                                            </span>
                                        </p>
                                        <p class="mb-1 text-muted">
                                            رقم المحامي :
                                            <span class="mb-0">{{ lawyer.id }}</span>
                                        </p>
                                    </div>
                                    <div class="d-flex align-self-end h-50">
                                        <a href="{% url 'service:order_form' lawyer.id %}"
                                           class="law-btn btn btn-outline-dark align-items-end">اطلب الخدمة</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

Excellency/main/templates/main/post.html
<!--djlint:off H021 H006-->
{% extends "base/base.html" %}
{% block title %}
    مجتمع المحامين
{% endblock title %}
{% block css %}
    <style>
        .card-post {
            border: 1px solid #e3e3e3;
            border-radius: 10px;
            margin-bottom: 20px;
            background-color: #ffffff;
            padding: 20px;
            transition: box-shadow 0.3s ease-in-out;
        }

        .card-post:hover {
            box-shadow: 0px 6px 12px rgba(0, 0, 0, 0.15);
        }


        .avatar-container {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            overflow: hidden;
        }

        .avatar {
            width: 100%;
            height: 100%;
        }

        .info-container {
            margin-left: 15px;
        }

        .title-post {
            font-size: 20px;
            color: #333;
        }

        .time {
            font-size: 14px;
            color: #999;
        }

        .image {
            max-width: 100%;
            border-radius: 10px;
            margin-top: 10px;
            border: 1px solid;
        }

        .post-description {
            margin-top: 20px;
        }

        .stats {
            margin-top: 20px;
        }

        .stat-item {
            margin-right: 10px;
        }
    </style>
{% endblock css %}
{% block content %}
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <div class="card-post mt-3">
                    <div class="card-body-post justify-content-center">
                        <div class="post-heading rounded-3">
                            <div class="avatar-container">
                                <img src="{{ post.author.lawyer_profile.image.url }}"
                                     class="img-circle avatar"
                                     alt="user profile image">
                            </div>
                            <div class="info-container">
                                <div class="title-post h5 text-end mt-2">
                                    <a href="{% url "account:profile_view" post.author.id %}"><b>{{ post.author.full_name }}</b></a>
                                </div>
                            </div>
                        </div>
                        {% if post.image %}
                            <hr>
                            <div class="d-flex justify-content-center post-image p-2 ">
                                <img src="{{ post.image.url }}" class="image rounded-3" alt="image post">
                            </div>
                        {% else %}
                            <br>
                        {% endif %}
                        <div class="post-description mt-3">
                            <h5>العنوان : {{ post.title }}</h5>
                            <p class="me-4 mb-4 border-1">
                                <br>
                                {{ post.content }}
                            </p>
                            <h6 class="text-muted time">{{ post.timestamp }}</h6>
                            <div class="stats align-items-center">
                                <a href="{% url 'main:like_post' post.id %}"
                                   class="btn btn-default stat-item">
                                    <i class="fa fa-thumbs-up icon"></i> {{ post.total_likes }}
                                </a>
                                <a href="{% url 'main:bookmark_post' post.id %}"
                                   class="btn btn-default stat-item">
                                    <i class="fa fa-bookmark" aria-hidden="true"></i> {{ post.total_bookmarks }}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

Excellency/main/templates/main/post_lawyers.html
<!--djlint:off H021 H006-->
{% extends "base/base.html" %}
{% block title %}
    مجتمع المحامين
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <div class="row justify-content-center">
            {% if posts %}
                {% for post in posts %}
                    <div class="col-md-7">
                        <div class="card-post mt-3">
                            <div class="card-body-post justify-content-center">
                                <div class="post-heading rounded-3">
                                    <div class="avatar-container">
                                        <img src="{{ post.author.lawyer_profile.image.url }}"
                                             class="img-circle avatar"
                                             alt="user profile image">
                                    </div>
                                    <div class="info-container">
                                        <div class="title-post h5 text-end mt-2">
                                            <a href="{% url "account:profile_view" post.author.id %}"><b>{{ post.author.full_name }}</b></a>
                                        </div>
                                    </div>
                                </div>
                                {% if post.image %}
                                    <hr>
                                    <div class="d-flex justify-content-center post-image p-2 ">
                                        <img src="{{ post.image.url }}" class="image rounded-3" alt="image post">
                                    </div>
                                {% else %}
                                    <br>
                                {% endif %}
                                <div class="post-description mt-3">
                                    <a href="{% url "main:post_view" post.id %}">
                                        <h5>العنوان : {{ post.title }}</h5>
                                    </a>
                                    <p class="me-4 mb-4 border-1">
                                        <br>
                                        {{ post.content }}
                                    </p>
                                    <h6 class="text-muted time">{{ post.timestamp }}</h6>
                                    <div class="stats align-items-center">
                                        <a href="{% url 'main:like_post' post.id %}"
                                           class="btn btn-default stat-item">
                                            <i class="fa fa-thumbs-up icon"></i> {{ post.total_likes }}
                                        </a>
                                        <a href="{% url 'main:bookmark_post' post.id %}"
                                           class="btn btn-default stat-item">
                                            <i class="fa fa-bookmark" aria-hidden="true"></i> {{ post.total_bookmarks }}
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-md-12">
                    <p class="fw-bold text-center mt-5">لا يوجد منشورات</p>
                </div>
            {% endif %}
        </div>
    </div>
    {% csrf_token %}
    <style>
        .card-post {
            border: 1px solid #e3e3e3;
            border-radius: 10px;
            margin-bottom: 20px;
            background-color: #ffffff;
            padding: 20px;
            transition: box-shadow 0.3s ease-in-out;
        }

        .card-post:hover {
            box-shadow: 0px 6px 12px rgba(0, 0, 0, 0.15);
        }


        .avatar-container {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            overflow: hidden;
        }

        .avatar {
            width: 100%;
            height: 100%;
        }

        .info-container {
            margin-left: 15px;
        }

        .title-post {
            font-size: 20px;
            color: #333;
        }

        .time {
            font-size: 14px;
            color: #999;
        }

        .image {
            max-width: 100%;
            border-radius: 10px;
            margin-top: 10px;
            border: 1px solid;
        }

        .post-description {
            margin-top: 20px;
        }

        .stats {
            margin-top: 20px;
        }

        .stat-item {
            margin-right: 10px;
        }
    </style>
{% endblock content %}