Excellency/Excellency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('service/', include("service.urls")),
    path("account/", include("account.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Excellency/main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path("", views.index_view, name="index_view"),
    path("lawyers", views.lawyers_view, name="lawyers_view"),
    path("contactus", views.contactus_view, name="contactus_view"),
    path("contact_messages", views.contact_messages, name="contact_messages"),
    path("admin_view", views.admin_view, name="admin_view"),
    path('lawyer_details/<user_id>', views.lawyer_details_view, name='lawyer_details'),
    path('post/', views.post_list, name='post_list'),
    path("verification/<user_id>/", views.verification, name="verification"),
    path('post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('post/<int:post_id>/', views.post_view, name='post_view'),

    path('post/<int:post_id>/bookmark/', views.bookmark_post, name='bookmark_post'),
    path('contact/success/', views.contact_success, name='contact_success'),

]

Excellency/service/urls.py
from django.urls import path
from . import views

app_name = "service"

urlpatterns = [
    #     path("", views.sign_up_view, name="sign_up_view"),
    path('order/<lawyer_id>/', views.order_form, name='order_form'),

    path('payment/<order_id>/', views.payment_view, name='payment_view'),
    path('<order_id>/chat/', views.chat_view, name='chat_view'),
    path('orders/', views.current_orders, name='current_orders_view'),
    path('previous_orders/', views.previous_orders, name='previous_orders'),
    path('order_details/<order_id>/', views.order_details, name='order_details'),
    path('offer/add/', views.add_offer, name='add_offer'),
    path('rating/', views.rating_view, name='rating_view'),
]

Excellency/service/models.py
from django.db import models
from account.models import User, Specialty

legal_advice = "استشارات قانونية"
drafting_contracts = "صياغة عقود"
warrant = "مذكرات"

Specialty_CHOICES = {
    'legal_advice': legal_advice,
    'drafting_contracts': drafting_contracts,
    'warrant': warrant
}


def service_file_upload_to(instance, filename):
    return "service/file/{}/{}".format(instance.id, filename)


class Service(models.Model):
    completed = "مكتمل"
    accepted = "مقبول"
    pending_accept_offer = "انتظار قبول السعر"
    pending = "قيد الانتظار"
    rejected = "مرفوض"
    STATUS_CHOICES = (
        ('completed', completed),
        ('accepted', accepted),
        ('pending_accept_offer', pending_accept_offer),
        ('pending', pending),
        ('rejected', rejected),
    )
    lawyer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="lawyer")
    customar = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="customar")
    order_type = models.ForeignKey(Specialty, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    content = models.TextField()
    file = models.FileField(
        upload_to=service_file_upload_to, blank=True, null=True)
    price = models.FloatField(
        blank=True, null=True)
    status = models.CharField(
        max_length=18, default=pending)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject


def group_based_upload_to(instance, filename):
    return "profiles/file/{}/{}".format(instance.user.id, filename)


class Comment(models.Model):
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, related_name="chat")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    file = models.FileField(
        upload_to=group_based_upload_to, blank=True, null=True)
    added_date = models.DateTimeField(auto_now_add=True)


class Payment(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=5, decimal_places=2)
    card_name = models.CharField(max_length=50)
    card_number = models.CharField(max_length=15)
    exp_date = models.DateField()
    paied = models.BooleanField(default=False)


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.OneToOneField(Service, on_delete=models.CASCADE, related_name="rating")
    comment = models.TextField(max_length=250, blank=True, null=True)
    rate = models.IntegerField(default=None)

Excellency/service/views.py
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from account.models import LawyerProfile, User
from django.contrib.auth.decorators import login_required
from service.models import Comment, Rating, Service, Specialty
from django.db.models import Q
# Create your views here.


@login_required(login_url='/account/login')
def order_form(request: HttpRequest, lawyer_id):
   try:
      lawyer = User.objects.get(pk=lawyer_id)
      if request.user == lawyer:
         return render(request, "404.html")
      if request.method == 'POST':
         order = Service.objects.create(lawyer=lawyer,
                                        customar=request.user,
                                        order_type=Specialty.objects.get(
                                            pk=request.POST['service']),
                                        subject=request.POST['subject'],
                                        content=request.POST['message'],
                                        file=request.FILES.get('file'))
         return redirect("service:order_details", order_id=order.id)
   except User.DoesNotExist:
      return render(request, "404.html")

   return render(request, 'service/Service-request-form.html', {"lawyer": lawyer})


@login_required(login_url="/account/login")
def payment_view(request: HttpRequest, order_id):
   order = get_object_or_404(Service, id=order_id)
   if request.method == "POST":
      order.status = order.accepted
      order.save()
      return redirect("service:order_details", order_id=order.id)
   return render(request, 'service/payment.html', {"order": order})


@login_required(login_url="/account/login")
def chat_view(request: HttpRequest, order_id):
   order = get_object_or_404(Service, id=order_id)
   try:
      lawyer = order.lawyer
      customar = order.customar
      if not (request.user == lawyer or request.user == customar):
         return render(request, "no_permission.html")
      order_comment: Comment = order.chat
      if request.method == "POST":
         content = request.POST["content"]

         Comment.objects.create(
            service=order, user=request.user, content=content, file=request.FILES.get("file"))
         return redirect(request.path+"#message-input")


   except Exception as e:
      print(e)
   return render(request, 'service/chat.html', {"order":order,"comments": order_comment.all()})


@login_required(login_url="/account/login")
def current_orders(request):
   user = request.user
   orders = Service.objects.filter(Q(lawyer=user) | Q(customar=user))
   orders = orders.exclude(Q(status=Service.completed)| Q(status=Service.rejected))

   return render(request, 'service/Lawyers_orders.html', {"orders": orders})


@login_required(login_url="/account/login")
def previous_orders(request:HttpRequest):
   user = request.user
   orders = Service.objects.filter(Q(lawyer=user) | Q(customar=user))
   orders =orders.filter(Q(status=Service.completed)|Q(status=Service.rejected))
   return render(request, 'service/previous_orders.html',{"orders":orders})


@login_required(login_url="/account/login")
def order_details(request: HttpRequest, order_id):
   user = request.user
   order = Service.objects.get(id=order_id)

   if not (order.lawyer == user or order.customar == user):
      return render(request, "no_permission.html")

   if request.method == "POST":
      if "reject-btn" in request.POST:
         order.status = request.POST.get("status", order.status)
         order.save()
         return redirect("service:order_details",order_id=order.id)

      if "make_offer" in request.POST:
         order.price = request.POST.get("price")
         order.status = request.POST.get("status", order.status)
         order.save()
         return redirect("service:order_details",order_id=order.id)
      if "completed-btn" in request.POST: 
         order.status = request.POST.get("status", order.status)
         order.save()

         return redirect("service:order_details",order_id=order.id)
      
      if "rating-submit" in request.POST and request.user.role == "Customar": 
         comment=request.POST.get('comment')
         rate=request.POST.get('rating')
         if rate:
               review=Rating.objects.create(service=order,user=request.user,comment=comment,rate=rate)
               review.save()
               return redirect("service:order_details",order_id=order.id)
   return render(request, 'service/order_details.html', {"order": order,
                                                         "status_choices": dict(Service.STATUS_CHOICES)})


def add_offer(request):
   return render(request, 'service/add_offer.html')


def rating_view(request):
   
   return render(request, 'service/rating.html')

Excellency/service/templates/service/Lawyers_orders.html
<!--djlint:off H021-->
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    طلب الخدمة
{% endblock title %}
{% block content %}
    {% include "account/sidebar.html" %}
    <div class="container mt-4 w-50 mt-5">
        <ul class="nav nav-tabs mb-4">
            <li class="nav-item p-2">
                <a class="nav-link"
                   href="{% url 'service:current_orders_view' %}"
                   style="color: #ca9e67">الطلبات الحالية</a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link"
                   href="{% url 'service:previous_orders' %}"
                   style="color: #ca9e67">الطلبات السابقة</a>
            </li>
        </ul>
    </div>
    <div class="container mt-4 ">
        <div class="row justify-content-center">
            {% for order in orders %}
                <div class="col-md-8">
                    <div class="card-law-order mb-2">
                        <div class="card-body-law">
                            <h5 class="card-title">
                                رقم الطلب #<span>{{ order.id }}</span>
                            </h5>
                            <p class="card-text">
                                {% if request.user.role == "Lawyer" %}
                                    عميل : <span>{{ order.customar.full_name }}</span>
                                {% elif request.user.role == "Customar" %}
                                    المحامي : <span>{{ order.lawyer.full_name }}</span>
                                {% endif %}
                            </p>
                            <p class="card-text">
                                نوع الخدمة : <span>{{ order.order_type }}</span>
                            </p>
                            <p class="card-text">
                                الحالة : <span>{{ order.status }}</span>
                            </p>
                            <div class="d-flex justify-content-end g-4">
                                <a href="{% url "service:order_details" order.id %}"
                                   class="btn btn-outline-dark me-2">تفاصيل الطلب</a>
                                {% if request.user.role == "Lawyer" and order.status == status_choices.pending %}
                                    <form action="{% url "service:order_details" order.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="status" value="{{ status_choices.rejected }}">
                                        <button type="submit" name="reject-btn" class="btn btn-danger me-2">غير مهتم</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

Excellency/service/templates/service/Service-request-form.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    طلب الخدمة
{% endblock title %}
{% block content %}
    <div class="custom-container container w-75 mt-5 pt-5">
        <form action="{% url "service:order_form" lawyer.id %}"
              method="post"
              enctype="multipart/form-data"
              class="service-form">
            {% csrf_token %}
            <div class="row justify-content-center">
                <h2 class="service-order text-center">طلب الخدمة</h2>
                <div class="col-md-6">
                    <div class="service-order-input">
                        <label for="subject" class="form-label service-order">الموضوع</label>
                        <input type="subject"
                               class="form-control"
                               id="subject"
                               name="subject"
                               required>
                    </div>
                    <div class="service-order-input">
                        <label for="message" class="form-label service-order">تفاصيل الطلب</label>
                        <textarea class="form-control" id="message" name="message" rows="5" required></textarea>
                    </div>
                </div>
                <div class="col-md-6 pt-4 mt-3">
                    <div class="service-order-input">
                        <select class="form-select" id="service" name="service" required>
                            {% for sp in lawyer.lawyer_profile.specialty.all %}<option value="{{ sp.id }}">{{ sp.name }}</option>{% endfor %}
                        </select>
                    </div>
                    <div class="service-order-input">
                        <div class="file-order mb-3">
                            <label for="file" class="form-label service-order">
                                <h5 class="text-decoration-underline">
                                    تحميل ملف <i class="fa fa-upload me-2 ms-3" aria-hidden="true"></i>
                                </h5>
                            </label>
                            <input type="file"
                                   class="form-control"
                                   id="file"
                                   name="file"
                                   onchange="displayFileName(this)">
                            <span id="file-name" class="file-name"></span>
                        </div>
                    </div>
                    <div class="d-grid">
                        <button type="submit" class="btn btn-dark btn-block">إرسال الطلب</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <style>
        .custom-container {
            background-color: #f8f9fa;
            border-radius: 25px 0px 25px 0px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .service-order {
            color: #343a40;
        }

        .service-order-input {
            margin-bottom: 20px;
        }

        .file-order {
            display: flex;
            align-items: flex-end;
        }

        .file-order i {
            font-size: 1.2rem;
            color: #6c757d;
        }

        .file-name {
            display: none;
        }

        .form-label:hover .file-name {
            display: inline;
        }


        .service-form input[type="file"] {
            display: none;
        }

        .service-form label[for="file"] {
            cursor: pointer;
        }

        .btn-dark {
            background-color: #343a40;
            border-color: #343a40;
        }

        .btn-dark:hover {
            background-color: #23272b;
            border-color: #23272b;
        }
    </style>
    <script>
        function displayFileName() {
            const input = document.getElementById('file');
            const label = document.querySelector('.file-order .form-label');

            if (input.files.length > 0) {
                label.innerHTML = `<h5 class="text-decoration-underline"> تحميل ملف <i class="fa fa-upload me-2 ms-3" aria-hidden="true"></i>${input.files[0].name}</h5>`;
            } else {
                label.innerHTML = '<h5 class="text-decoration-underline"> تحميل ملف <i class="fa fa-upload me-2 ms-3" aria-hidden="true"></i></h5>';
            }
        }
    </script>
{% endblock content %}

Excellency/service/templates/service/chat.html
<!--djlint:off H021 H006-->
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    محادثة
{% endblock title %}
{% block content %}
    {% include "account/sidebar.html" %}
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <a href="{% url 'service:order_details' order.id %}"
                   class="btn btn-outline-dark"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                <h2 class="mb-4 text-center">المحادثة</h2>
                <ul class="list-unstyled chat-list" id="chat-messages">
                    {% for comment in comments %}
                        <li class="chat-message
                                   {% if comment.user == request.user %}
                                       right
                                   {% else %}
                                       left
                                   {% endif %}
                                   w-50">
                            <div class="message-content">
                                <div class="message-header ">
                                    <img src="{% if comment.user.role == "Lawyer" %}{{ comment.user.lawyer_profile.image.url }}{% else %}{{ comment.user.customar_profile.image.url }}{% endif %}"
                                         alt="avatar"
                                         class="rounded-circle ms-3 shadow"
                                         width="40">
                                    <div>
                                        <p class="sender-name">{{ comment.user.full_name }}</p>
                                        <p class="message-time">{{ comment.added_date }}</p>
                                    </div>
                                </div>
                                <p class="message-text">{{ comment.content }}</p>
                            </div>
                            <div class="d-flex justify-content-end ms-4">
                                {% if comment.file %}<a target="_blank" cl href="{{ comment.file.url }}">الملف</a>{% endif %}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <hr>
                {% if not order.status == order.completed %}
                    <form action="{{ request.path }}"
                          method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="chat-sum input-group mt-4 mb-4">
                            <input id="message-input"
                                   name="content"
                                   class="input-chat form-control rounded-4"
                                   placeholder="اكتب رسالتك هنا..." />
                            <label for="file-upload"
                                   class="ico-chat btn btn-outline-dark rounded-4 align-content-center">
                                <i class="fas fa-file-upload"></i>
                            </label>
                            <input id="file-upload"
                                   type="file"
                                   name="file"
                                   class="form-control"
                                   style="display: none">
                            <button id="send-button"
                                    class="ico-chat btn btn-outline-dark rounded-4"
                                    type="submit">
                                <i class="fas fa-paper-plane"></i>
                            </button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const chatMessages = document.getElementById('chat-messages');
            chatMessages.scrollTop = chatMessages.scrollHeight;
        });
    </script>
{% endblock content %}

Excellency/service/templates/service/order_details.html
<!--djlint:off H021 H023-->
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    طلب الخدمة
{% endblock title %}
{% block content %}
    {% include "account/sidebar.html" %}
    <div class="container mt-4 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card-details">
                    <div class="card-body">
                        <h5 class="card-title">
                            رقم الطلب #<span>{{ order.id }}</span>
                        </h5>
                        <hr>
                        <p class="card-text">
                            عميل : <span>{{ order.customar.full_name }}</span>
                        </p>
                        <p class="card-text">
                            المحامي : <span>{{ order.lawyer.full_name }}</span>
                        </p>
                        <p class="card-text">
                            نوع الخدمة : <span>{{ order.order_type }}</span>
                        </p>
                        <p class="card-text">
                            حالة الخدمة : <span>{{ order.status }}</span>
                        </p>
                        {% if order.file %}
                            <p class="card-text">
                                ملف:
                                <a href="{{ order.file.url }}" target="_blank">انقر هنا</a>
                            </p>
                        {% endif %}
                        {% if order.status == status_choices.pending_accept_offer %}
                            <p class="card-text">
                                السعر  المعروض : <span>{{ order.price }}</span>
                            </p>
                        {% endif %}
                        <h3 class="mt-4 text-113345">
                            عنوان الطلب : <span class="fs-5 bg-gradient p-2 rounded-4 mx-3">{{ order.subject }}</span>
                        </h3>
                        <h3 class="mt-4 text-113345">وصف الطلب</h3>
                        <div class="row justify-content-start">
                            <div class="col-md-8">
                                <div class="card-law-order mb-2">
                                    <div class="card-body-law">
                                        <p class="card-text">{{ order.content }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex mt-5 g-4">
                            {% if request.user.role == "Customar" and order.status == status_choices.pending_accept_offer %}
                                <a href="{% url "service:payment_view" order.id %}"
                                   class="btn btn-outline-primary me-2">الدفع</a>
                            {% endif %}
                            {% if request.user.role == "Lawyer" and order.status == status_choices.pending %}
                                <button type="button"
                                        class="btn btn-outline-dark me-2"
                                        data-bs-toggle="modal"
                                        data-bs-target="#offerModal">إضافة عرض</button>
                                <form action="{% url "service:order_details" order.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="status" value="{{ status_choices.rejected }}">
                                    <button type="submit" name="reject-btn" class="btn btn-danger me-2">غير مهتم</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="d-flex gap-2">
                    {% if request.user.role == order.customar.role or request.user.role == order.lawyer.role %}
                        {% if order.status == status_choices.accepted or order.status == status_choices.completed %}
                            <a href="{% url "service:chat_view" order.id %}"
                               class="btn btn-success me-2">المحادثة</a>
                        {% endif %}
                    {% endif %}
                    {% if order.status == status_choices.accepted %}
                        <form action="{% url "service:order_details" order.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="status" value="{{ status_choices.completed }}">
                            <button type="submit" name="completed-btn" class="btn btn-outline-dark ">إنهاء الطلب</button>
                        </form>
                    {% endif %}
                </div>
                {% if order.status == status_choices.completed %}
                    {% if not order.rating and request.user.role == "Customar" %}
                        {% include "service/rating.html" %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="modal fade"
         id="offerModal"
         tabindex="-1"
         aria-labelledby="offerModalLabel"
         aria-hidden="true">
        <div class="modal-dialog  modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header ">
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url "service:order_details" order.id %}"
                          method="post"
                          class="d-flex justify-content-center flex-column">
                        {% csrf_token %}
                        <h3 class=" text-dark ">إضافة مبلغ</h3>
                        <div class="input-group mb-3">
                            <span class="input-group-text">ريال</span>
                            <input type="text"
                                   class="form-control"
                                   name="price"
                                   aria-label="السعر (to the nearest dollar)">
                            <input type="hidden"
                                   name="status"
                                   value="{{ status_choices.pending_accept_offer }}">
                        </div>
                        <button type="submit" name="make_offer" class="btn btn-outline-dark">تقديم العرض</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

Excellency/service/templates/service/previous_orders.html
<!--djlint:off H021-->
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    طلب الخدمة
{% endblock title %}
{% block content %}
    {% include "account/sidebar.html" %}
    <div class="container mt-4 w-50 mt-5">
        <ul class="nav nav-tabs mb-4">
            <li class="nav-item p-2">
                <a class="nav-link"
                   href="{% url 'service:current_orders_view' %}"
                   style="color: #ca9e67">الطلبات الحالية</a>
            </li>
            <li class="nav-item p-2">
                <a class="nav-link"
                   href="{% url 'service:previous_orders' %}"
                   style="color: #ca9e67">الطلبات السابقة</a>
            </li>
        </ul>
    </div>
    <div class="container mt-4 ">
        <div class="row justify-content-center">
            {% for order in orders %}
                <div class="col-md-8">
                    <div class="card-law-order mb-2">
                        <div class="card-body-law">
                            <h5 class="card-title">
                                رقم الطلب #<span>{{ order.id }}</span>
                            </h5>
                            <p class="card-text">
                                {% if request.user.role == "Lawyer" %}
                                    عميل : <span>{{ order.customar.full_name }}</span>
                                {% elif request.user.role == "Customar" %}
                                    المحامي : <span>{{ order.lawyer.full_name }}</span>
                                {% endif %}
                            </p>
                            <p class="card-text">
                                نوع الخدمة : <span>{{ order.order_type }}</span>
                            </p>
                            <p class="card-text">
                                الحالة : <span>{{ order.status }}</span>
                            </p>
                            <div class="d-flex justify-content-end g-4">
                                <a href="{% url "service:order_details" order.id %}"
                                   class="btn btn-outline-dark me-2">تفاصيل الطلب</a>
                                {% if request.user.role == "Lawyer" and order.status == status_choices.pending %}
                                    <form action="{% url "service:order_details" order.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="status" value="{{ status_choices.rejected }}">
                                        <button type="submit" name="reject-btn" class="btn btn-danger me-2">غير مهتم</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}