Excellency/Excellency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('service/', include("service.urls")),
    path("account/", include("account.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Excellency/account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("sign_up/", views.sign_up_view, name="sign_up_view"),
    # path("user/", views.user_profile_view, name="user_profile_view"),
    #     path("user/<user_name>/",views.user_profile_view, name="user_profile_view"),
    path("profile/<user_id>/update/",views.update_profile_view, name="update_profile_view"),
        # path("profile/update/",views.update_profile_view, name="update_profile_view"),

    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view"),
    path("lawyer/<user_id>/profile/",views.profile_view, name="profile_view"),
    path("account_balance/", views.account_balance, name="account_balance"),
    path('posts/<user_id>/', views.my_post, name='my_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post')

]

Excellency/main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path("", views.index_view, name="index_view"),
    path("lawyers", views.lawyers_view, name="lawyers_view"),
    path("contactus", views.contactus_view, name="contactus_view"),
    path("contact_messages", views.contact_messages, name="contact_messages"),
    path("admin_view", views.admin_view, name="admin_view"),
    path('lawyer_details/<user_id>', views.lawyer_details_view, name='lawyer_details'),
    path('post/', views.post_list, name='post_list'),
    path("verification/<user_id>/", views.verification, name="verification"),
    path('post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('post/<int:post_id>/', views.post_view, name='post_view'),

    path('post/<int:post_id>/bookmark/', views.bookmark_post, name='bookmark_post'),
    path('contact/success/', views.contact_success, name='contact_success'),

]

Excellency/main/models.py
from django.db import models
from main import validator
from account.models import User

class Contactus(models.Model):
   full_name = models.CharField(max_length=50, blank=False)
   email = models.EmailField(blank=False, validators=[
                             validator.validate_email])
   subject = models.CharField(max_length=120, blank=False)
   message = models.TextField(blank=False)
   created_at = models.DateTimeField(auto_now_add=True)
   
def post_image_upload_to(instance, filename):
   return "post/images/{}/{}".format(instance.author.id, filename)

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to=post_image_upload_to, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
     
    def total_likes(self):
        return Like.objects.filter(post=self).count()

    def total_bookmarks(self):
        return Bookmark.objects.filter(post=self).count()
     
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} likes {self.post.title}'
     
class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} bookmarks {self.post.title}'

Excellency/main/views.py
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, render, redirect
from main.models import Contactus, Post, Like, Bookmark
from service.models import Service
from account.models import User, Specialty, LawyerProfile
from django.db.models import Count, Sum
from django.db.models import F
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import global_settings as settings
from django.core.mail import send_mail

email_from = settings.EMAIL_HOST_USER


def index_view(request: HttpRequest):
    order_num = Service.objects.all().count()
    lawyers_num = User.objects.filter(role="Lawyer").count()
    customar_num = User.objects.filter(role="Customar").count()
    return render(request, "main/index.html", {"order_num": order_num,
                                               "lawyers_num": lawyers_num,
                                               "customar_num": customar_num})


def contactus_view(request: HttpRequest):
    msg = None
    try:
        if request.method == "POST":
            Contactus.objects.create(full_name=request.POST.get('full_name'),
                                     email=request.POST.get('email'),
                                     subject=request.POST.get('subject'),
                                     message=request.POST.get('message'),
                                     )
            msg = "تم ارسال رسالتك بنجاح"
            return redirect("main:contact_success")
    except Exception as e:
        msg = e
    return render(request, "main/contactus.html", {'msg': msg})


def lawyers_view(request: HttpRequest):
    try:
        lawyers = User.objects.filter(
            role="Lawyer", lawyer_profile__certified=True)
        spcialities = Specialty.objects.all()
        if "sort" not in request.GET:
            lawyers.order_by("id")

        if "lawyer_name" in request.GET:
            lawyers = lawyers.filter(
                full_name__contains=request.GET.get("lawyer_name")
            )
        if "spcialties" in request.GET:
            spcialities_filter = request.GET.getlist("spcialties")
            lawyers = lawyers.filter(
                lawyer_profile__specialty__in=spcialities_filter).annotate(Count("id"))
        if "sort" in request.GET:
            if request.GET.get("sort") == "user_name_a_z":
                lawyers = lawyers.order_by("full_name")
            elif request.GET.get("sort") == "user_name_z-a":
                lawyers = lawyers.order_by("-full_name")
            elif request.GET.get("sort") == "rating_top":
                lawyers = lawyers.annotate(total=Sum("lawyer__rating__rate")).order_by("-total")
        if "clear" in request.GET:
            print(request.path)
            return redirect(request.path)
    except Exception as e:
        print(e)
    return render(request, "main/lawyers.html", {"lawyers": lawyers, "specialities": spcialities})


@login_required(login_url='/account/login')
def contact_messages(request: HttpRequest):
    if not (request.user.is_staff or request.user.is_superuser):
        return render(request, "no_permission.html")
    messages = Contactus.objects.all()

    return render(request, 'main/contact_messages.html', {'messages': messages})


@login_required(login_url='/account/login')
def admin_view(request: HttpRequest):
    if not (request.user.is_staff or request.user.is_superuser):
        return render(request, "no_permission.html")
    lawyer_profiles = LawyerProfile.objects.all()
    return render(request, 'main/admin.html', {'lawyer_profiles': lawyer_profiles})


def lawyer_details_view(request: HttpRequest, user_id):
    user = User.objects.get(id=user_id)
    return render(request, 'main/lawyer_details.html', {"user": user})


@login_required(login_url='/account/login')
def verification(request: HttpRequest, user_id):
    if not (request.user.is_staff or request.user.is_superuser):
        return render(request, "no_permission.html")
    user = User.objects.get(id=user_id)

    recipient_list = [user.email, ]
    if "accept" in request.POST:
        user.lawyer_profile.certified = True
        user.lawyer_profile.save()
        # send mail
        subject = 'تم توثيق حسابك في موقع المعالي للمحاماة'
        message = f'''مرحبا  {user.full_name},
        تم توثيق حسابك
        {request.build_absolute_uri("/")}
        '''
        send_mail(subject, message, email_from, recipient_list)

    if "reject" in request.POST:
        user.lawyer_profile.certified = False
        user.lawyer_profile.save()
        # send mail
        subject = 'تم الغاء توثيق حسابك في موقع المعالي للمحاماة'
        message = f'''مرحبا  {user.full_name},
         نأسف لاخبارك انه تم الغاء توثيق حسابك لانتهاكك قوانين الموقع
        {request.build_absolute_uri("/")}
        '''
        send_mail(subject, message, email_from, recipient_list)

    return redirect("main:admin_view")


@login_required(login_url='/account/login')
def post_list(request: HttpRequest):
    posts = Post.objects.all()
    return render(request, 'main/post_lawyers.html', {'posts': posts})


def post_view(request: HttpRequest, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'main/post.html', {'post': post})


def like_post(request: HttpRequest, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user
    if user.is_authenticated:
        like, created = Like.objects.get_or_create(user=user, post=post)
        if not created:
            like.delete()
    return redirect(reverse('main:post_list'))


def bookmark_post(request: HttpRequest, post_id):
    try:
        if not request.user.is_authenticated:
            return redirect("account:login_view")
        post = Post.objects.get(pk=post_id)

        bookmarked_post = Bookmark.objects.filter(user=request.user, post=post).first()

        if not bookmarked_post:

            bookmark = Bookmark(user=request.user, post=post)
            bookmark.save()
        else:

            bookmarked_post.delete()

    except Exception as e:
        print(e)

    return redirect("main:post_list")


def contact_success(request):
    return render(request, 'main/contact_success.html')

Excellency/main/templates/base/base.html
{# djlint:off H030,H031 H020 D018 #}
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
  <head>
    <meta charset="utf-8" />
    {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-5zVjzDOQ+1FhzCU1UM8y++iPjsqSmE/W+nUJg8rWvBvSfo/K0UO5RBDAX+HSLKxZ" crossorigin="anonymous"> {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" />
    <link href="{% static "css/stayle.css" %}" rel="stylesheet" />
    {% block css %}
    {% endblock css %}
    {% comment %} <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" /> {% endcomment %}
    <script src="{% static "js/index.js" %}"></script>
    {% block js %}
    {% endblock js %}
    <link rel="icon" href="{% static "icons/gold-icon.png" %}" sizes="any" type="image/svg+xml">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Amiri:ital,wght@0,400;0,700;1,400;1,700&family=Archivo+Black&family=Caveat+Brush&family=Racing+Sans+One&display=swap" rel="stylesheet">
  </head>
  <body>
    <main>
      <header>
        {% include "base/navbar.html" %}
      </header>
      <section class="container-bady overflow-x-hidden">
        {% block content %}
        {% endblock content %}
      </section>
      {% include "base/footer.html" %}
    </main>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static "js/index.js" %}"></script>
  </body>
</html>

Excellency/main/templates/base/footer.html
{# djlint:off H006,H021 #}
{% load static %}
<style>
  footer {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
    background-color: #113345;
    padding-top: 2px;
}

footer img {
    max-width: 100%;
}

@media (max-width: 768px) {
    footer {
        justify-content: center;
        text-align: center;
    }
    footer .col-md-2, footer .col-md-4, footer .col-md-6 {
        width: 100%;
        display: block;
    }
    footer .d-flex {
        justify-content: center;
        flex-direction: row;
        flex-wrap: wrap;
    }
}

@media (max-width: 576px) {
    footer .d-flex {
        flex-direction: column;
    }
    footer ul {
        padding: 0;
    }
    footer ul li {
        margin: 0 10px;
    }
}

</style>
{% load static %}
<footer class="d-flex flex-wrap justify-content-center align-items-center border-top pt-2" style="background-color:#113345">
    <div class="col-12 col-sm-4 text-center mb-3 mb-sm-0">
        <img src="{% static 'icons/gold-icon.png' %}" width="50px" alt="">
    </div>
    <div class="col-12 col-sm-4 text-center mb-3 mb-sm-0">
        <p class="text-gold fs-6">©2024 المعالي, جميع الحقوق محفوظة</p>
    </div>
    <div class="col-12 col-sm-4 text-center">
        <ul class="list-unstyled d-flex flex-row justify-content-center">
            <li class="mx-2">
                <a href="#">
                    <i class="fa-brands fa-square-x-twitter"></i>
                </a>
            </li>
            <li class="mx-2">
                <a href="#">
                    <i class="fa-brands fa-square-instagram"></i>
                </a>
            </li>
            <li class="mx-2">
                <a href="#">
                    <i class="fa-brands fa-linkedin"></i>
                </a>
            </li>
        </ul>
    </div>
</footer>

Excellency/main/templates/base/navbar.html
{# djlint:off H006#}
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-sm navbar-light ">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand ms-5" href="{% url 'main:index_view' %}">
      <img src="{% static 'icons/gold-icon.png' %}"
           alt="Brand Image"
           height="60px">
    </a>
    <!-- Toggle button -->
    <button class="navbar-toggler me-2"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNavDropdown"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <i class="fa-solid fa-bars  text-gold" style="border: none;"></i>
    </button>
    <!-- Collapsible wrapper. -->
    <div class="collapse navbar-collapse justify-content-between"
         id="navbarNav">
      {% url "main:index_view" as home_page %}
      {% url "main:contactus_view" as contactus_page %}
      {% url "main:lawyers_view" as lawyers_page %}
      {% url "main:post_list" as post_list %}
      <!-- Left links -->
      <ul class="navbar-nav justify-content-between p-0 align-items-center flex-row-reverse">
        <li class="nav-item">
          <a class="nav-link
                    {% if request.path == contactus_page %}active{% endif %}"
             href="{{ contactus_page }}">تواصل</a>
        </li>
        <li class="nav-item">
          <a class="nav-link
                    {% if request.path == post_list %}active{% endif %}"
             href="{{ post_list }}">المنشورات</a>
        </li>
        <li class="nav-item">
          <a class="nav-link
                    {% if request.path == lawyers_page %}active{% endif %}"
             href="{{ lawyers_page }}">المحامين</a>
        </li>
        <li class="nav-item">
          <a class="nav-link
                    {% if request.path == home_page %}active{% endif %}"
             href="{{ home_page }}">الرئيسية</a>
        </li>
      </ul>
      <!-- Left links -->
      <div class="d-flex gap-2 justify-content-center">
        {% if not request.user.is_authenticated %}
          <a href="{% url 'account:sign_up_view' %}"
             type="button"
             class="btn nav-link btn-link px-3 me-2">تسجيل</a>
          <a href="{% url 'account:login_view' %}"
             class="btn nav-link btn-link px-3 me-2">تسجيل الدخول</a>
        {% else %}
          {% if request.user.is_superuser %}
            <a href="{% url 'main:admin_view' %}"
               class="btn nav-link btn-link px-3 me-2">لوحة التحكم</a>
          {% else %}
            <a href="{% url 'account:profile_view' request.user.pk %}"
               class="btn nav-link btn-link px-3 me-2">مرحبا {{ request.user.full_name }} |  حسابي</a>
          {% endif %}
          <a href="{% url 'account:logout_view' %}"
             class="btn nav-link btn-link px-3 me-2">تسجيل الخروج</a>
        {% endif %}
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->